name: Release

on:
  release:
    types: [released]
jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: Bump primary formula
        uses: mislav/bump-homebrew-formula-action@942e550c6344cfdb9e1ab29b9bb9bf0c43efa19b # v3.2
        if: "contains(github.ref, 'v2')"
        with:
          formula-name: zsh-job-queue@2
          formula-path: zsh-job-queue@2.rb
          homebrew-tap: olets/homebrew-tap
          commit-message: |
            feat({{formulaName}}): publish {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}

      - name: Bump 2.x formula
        uses: mislav/bump-homebrew-formula-action@942e550c6344cfdb9e1ab29b9bb9bf0c43efa19b # v3.2
        if: "contains(github.ref, 'v2')"
        with:
          formula-name: zsh-job-queue@2
          formula-path: zsh-job-queue@2.rb
          homebrew-tap: olets/homebrew-tap
          commit-message: |
            feat({{formulaName}}): publish {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}

      - name: Bump v1.x formula
        uses: mislav/bump-homebrew-formula-action@942e550c6344cfdb9e1ab29b9bb9bf0c43efa19b # v3.2
        if: "contains(github.ref, 'v1')"
        with:
          formula-name: zsh-job-queue@1
          formula-path: zsh-job-queue@1.rb
          homebrew-tap: olets/homebrew-tap
          commit-message: |
            feat({{formulaName}}): publish {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
