syntax = "All"
column_width = 120
line_endings = "Unix"
indent_type = "Spaces"  ## "Tabs"
indent_width = 2  ## 4
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Always"  ## "Never"
space_after_function_names = "Never"

[sort_requires]
enabled = false
