.TH "ZSH-JOB-QUEUE" 1 "August 19 2025" "job-queue 3.1.0" "User Commands"
.SH NAME
zsh\-job-queue \- manage a cross-session job queue
.SH SYNOPSIS

For full manual including options, visit https://zsh-job-queue.olets.dev/

\fBjob-queue pop\fR <\fIcommand\fR> <\fIscope\fR> <\fIid\fR>

\fBjob-queue push\fR <\fIcommand\fR> <\fIscope\fR> [<\fIdescription\fR> [<\fInew support ticket url\fR>]]

\fBjob-queue clear\fR <\fIscope\fR>

\fBjob-queue\fR (\fBhelp\fR | \fB\-\-help\fR)

\fBjob-queue\fR (\fB\-\-version\fR | \fB\-v\fR)

.SH DESCRIPTION
\fBjob-queue\fR manages a cross-session job queue.

.SH Commands
The following commands are available:

.IP \(bu
\fBjob-queue clear\fR <\fIscope\fR>

Removes all jobs queued in the specified scope.

.IP \(bu
\fBjob-queue pop\fR <\fIcommand\fR> <\fIscope\fR> <\fIid\fR>

Removes a job from the queue.

.IP \(bu
\fBjob-queue push\fR <\fIcommand\fR> <\fIscope\fR> [<\fIdescription\fR> [<\fInew support ticket url\fR>]]

Adds a job to the queue.

.IP \(bu
\fBjob-queue\fR (\fBhelp\fR | \fB\-\-help\fR)

Show the manpage.

.IP \(bu
\fBjob-queue\fR (\fB\-\-version\fR | \fB\-v\fR)

Show the current version.

.SH AUTHORS

Henry Bley\-Vroman <olets@olets.dev>
