import tailwindcss from "@tailwindcss/vite";
import { defineConfig } from "vitepress";
import { createTitle, normalize } from "vitepress/dist/client/shared.js";
import markdownItFootnote from "markdown-it-footnote";

const DESCRIPTION = "Global (cross-terminal) synchronous job queues for zsh.";
const FALLBACK_META_IMAGE = "zsh-job-queue-card.png";
const TITLE = "zsh-job-queue";
const ORIGIN = "https://zsh-job-queue.olets.dev";

function href(path = "") {
  return new URL(normalize(path), ORIGIN).href;
}

// https://vitepress.dev/reference/site-config
export default defineConfig({
  vite: { plugins: [tailwindcss()] },
  head: [
    // favicon generated by https://realfavicongenerator.net/
    [
      "link",
      {
        rel: "icon",
        type: "image/png",
        sizes: "96x96",
        href: "/favicon-96x96.png",
      },
    ],
    [
      "link",
      {
        rel: "icon",
        type: "image/svg+xml",
        href: "/favicon.svg",
      },
    ],
    [
      "link",
      {
        rel: "shortcut icon",
        href: "/favicon.ico",
      },
    ],
    [
      "link",
      {
        rel: "apple-touch-icon",
        sizes: "180x180",
        href: "/apple-touch-icon.png",
      },
    ],
    [
      "meta",
      {
        name: "apple-mobile-web-app-title",
        content: "zsh-job-queue",
      },
    ],
    [
      "link",
      {
        rel: "manifest",
        href: "/site.webmanifest",
      },
    ],

    // social metas
    ["meta", { property: "og:site_name", content: TITLE }],
    ["meta", { property: "og:type", content: "website" }],
    ["meta", { property: "og:image:width", content: "1200" }],
    ["meta", { property: "og:image:height", content: "630" }],
    ["meta", { name: "twitter:card", content: "summary_large_image" }],

    // Analytics
    [
      "script",
      {
        src: "https://cdn.usefathom.com/script.js",
        "data-site": "NPCTPDBT",
        "data-spa": "auto",
        defer: "true",
      },
    ],
    [
      "script",
      {
        src: "/js/analytics.js",
      },
    ],

    // Font
    [
      "link",
      {
        rel: "preconnect",
        href: "https://fonts.googleapis.com",
      },
    ],
    [
      "link",
      {
        rel: "preconnect",
        href: "https://fonts.gstatic.com",
        crossorigin: "true",
      },
    ],
    [
      "link",
      {
        href: "https://fonts.googleapis.com/css2?family=Fira+Code&display=swap",
        rel: "stylesheet",
      },
    ],
  ],
  transformPageData(pageData, ctx) {
    let pageDescription = pageData.frontmatter?.description;
    const pageHref = href(pageData.relativePath);
    const pageImage = href(
      pageData.frontmatter?.metaImage ?? FALLBACK_META_IMAGE,
    );
    const pageTitle = createTitle(ctx.siteConfig.site, pageData);

    if (!pageDescription) {
      pageDescription = ctx.siteConfig.site?.description;

      if (pageHref !== href()) {
        pageDescription = [ctx.siteConfig.site?.title, pageDescription]
          .filter((v) => Boolean(v))
          .join(": ");
      }
    }

    pageData.frontmatter.head ??= [];

    pageData.frontmatter.head.push(
      [
        "meta",
        {
          property: "og:image",
          content: pageImage,
        },
      ],
      [
        "meta",
        {
          name: "og:title",
          content: pageTitle,
        },
      ],
      [
        "meta",
        {
          property: "og:url",
          content: pageHref,
        },
      ],
      [
        "meta",
        {
          name: "twitter:image",
          content: pageImage,
        },
      ],
      [
        "meta",
        {
          name: "twitter:title",
          content: pageTitle,
        },
      ],
    );

    if (pageDescription) {
      pageData.frontmatter.head.push(
        [
          "meta",
          {
            name: "og:description",
            content: pageDescription,
          },
        ],
        [
          "meta",
          {
            name: "twitter:description",
            content: pageDescription,
          },
        ],
      );
    }
  },
  title: TITLE,
  description: DESCRIPTION,
  // https://vitepress.dev/reference/site-config#titletemplate
  titleTemplate: `:title :: ${TITLE}`, // to change delimiter from default pipe to play nice with Fathom event id format. also homepage frontmatter
  // https://vitepress.dev/reference/default-theme-last-updated
  lastUpdated: true,
  markdown: {
    externalLinks: {
      class: "vp-external-link-icon",
      target: "_self",
    },
    config: (md) => {
      md.use(markdownItFootnote);
    },
    theme: {
      light: "github-light-high-contrast",
      dark: "github-dark-high-contrast",
    },
  },
  srcExclude: ["vitepressignore"],
  sitemap: {
    hostname: href(),
  },
  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config

    editLink: {
      pattern: "https://github.com/olets/zsh-job-queue/edit/main/docs/:path",
    },

    logo: "/images/zsh-job-queue-logo.png",

    nav: [
      {
        text: "v3",
        items: [
          {
            text: "Major version",
            link: "",
          },
          {
            text: "v3",
            link: "/",
            target: "_self",
          },
          {
            text: "v2",
            link: "https://v2.zsh-job-queue.olets.dev",
            target: "_self",
          },
          {
            text: "v1",
            link: "https://v1.zsh-job-queue.olets.dev",
            target: "_self",
          },
        ],
      },
      {
        text: "Source, Changelog, License",
        link: "https://github.com/olets/zsh-job-queue/",
        target: "_self",
      },
      {
        text: "olets.dev",
        link: "https://olets.dev",
        target: "_self",
      },
    ],

    search: {
      provider: "local",
    },

    sidebar: [
      {
        text: "Overview",
        collapsed: false,
        items: [
          { text: "Introduction", link: "/" },
          { text: "Installation", link: "/installation" },
          { text: "What's new?", link: "/whats-new" },
        ],
      },
      {
        text: "Manual",
        collapsed: false,
        items: [
          { text: "Usage", link: "/usage" },
          { text: "Options", link: "/options" },
          { text: "Examples", link: "/examples" },
        ],
      },
      {
        link: "/migrating-between-versions.md",
        text: "Migrating between versions",
      },
      { text: "Contributing", link: "/contributing" },
    ],
  },
});
