---
name: Check links in README.md

on:
  schedule: [{cron: "0 1 * * *"}]
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker://dkhamsing/awesome_bot:latest
      with:
        args: /github/workspace/README.md --allow-timeout --allow-dupe --request-delay 1 --allow-redirect --white-list http://www.hawkwings.net/2007/03/03/scripts-to-automate-the-mailapp-envelope-speed-trick,http://lostechies.com/derickbailey/2012/09/08/screencasting-tip-resize-your-app-to-720p-1280x720-in-osx/,https://img.shields.io,https://git.herrbischoff.com
