/*
 * wallaby-core - v1.0.1650
 * https://wallabyjs.com
 * Copyright (c) 2014-2024 Wallaby.js - All Rights Reserved.
 *
 * This source code file is a part of wallaby-core and is a proprietary (closed source) software.

 * IMPORTANT:
 * Wallaby.js is a tool made by software developers for software developers with passion and love for what we do.
 * Pirating the tool is not only illegal and just morally wrong,
 * it is also unfair to other fellow programmers who are using it legally,
 * and very harmful for the tool and its future.
 */
var tape,testFiles,harness,results,tracer=global.$_$tracer,tapeInstalled=!1;try{tape=require("tape"),tapeInstalled=!0}catch(e){tracer.start(function(){tracer.reportGlobalError("tape node module is not found or the version is not supported, missing `npm install tape --save-dev`?\n"+(e.stack||""))}),module.exports={init:function(){return{configure:function(){}}}}}tapeInstalled&&(testFiles=[],harness=tape.getHarness({exit:!1,objectMode:!0}),results=harness._results,tracer.start(function(){testFiles.forEach(function(e){require(e)});function t(){for(var e;(e=function(e){if(!e._only)return e.tests.shift();do{var t=e.tests.shift();if(t&&e._only===t.name)return t}while(0!==e.tests.length)}(results))&&!p();)if(s(e),e.run(),!e.ended)return e.once("end",function(){p()||o(t)});results.emit("done")}var e=tracer.initialSpecId(),r=global.$_$session,n=!1,p=function(){return r!==global.$_$session},o="undefined"!=typeof setImmediate?setImmediate:process.nextTick,s=function(u){var t;p()||(u._testFile=tracer.entryFile(),t=u._cb,u._cb=function(){tracer.specSyncStart();try{if(!t)throw new Error("Test function is not defined.");t(u)}catch(e){u.fail(e.message,{error:e}),u.end(t?e:null)}finally{tracer.specSyncEnd()}},u.on("prerun",function(){p()||(u._id=++e,u._timeout=u._timeout||1e3,u._time=(new tracer._Date).getTime(),u._log=[],tracer.specStart(u._id,u.name))}),u.on("result",function(e){p()||u._log.push(e)}),u.on("test",function(e){p()||s(e)}),u.once("end",function(){if(!p()){var e=tracer.specEnd(),t=u._skip||u._todo,r=u._skip?"skipped":u._todo?"todo":"executed",n={id:u._id,timeRange:e,name:u.name,suite:[],status:r,time:(new tracer._Date).getTime()-u._time,log:[],hook:!1,testFile:u._testFile};if(!t)for(var o=0,s=u._log.length;o<s;o++){var a,i,c,l=u._log[o];n.success=n.success&&l.ok,!l.ok&&l.error&&(a={message:l.error.message,stack:l.actual&&l.actual.stack||l.error.stack},l.showDiff="equal"===l.operator||"notEqual"===l.operator||"deepEqual"===l.operator||"deepLooseEqual"===l.operator||"notDeepEqual"===l.operator||"notDeepLooseEqual"===l.operator,i=l.actual,c=l.expected,tracer.setAssertionData(l,a),"fail"!==l.operator&&"error"!==l.operator&&(a.message="Actual: "+tracer._inspect(i,5)+"\nExpected: "+tracer._inspect(c,5)),n.log.push(a))}n.log.length||delete n.log,tracer.result(n)}}))};tracer.started({total:"unknown number of"}),results.once("done",function(){n||p()||(n=!0,tracer.complete())}),t()}),module.exports={init:function(e){return testFiles=e,tape}});