# Compliant with /Users/s-a-c/dotfiles/dot-config/ai/guidelines.md v<checksum>
name: Publish Badges & Metrics

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Structure Audit
        run: |
          chmod +x tools/generate-structure-audit.zsh || true
          tools/generate-structure-audit.zsh

      - name: Generate Performance Badge
        run: |
          chmod +x tools/generate-perf-badge.zsh || true
          tools/generate-perf-badge.zsh 5

      - name: Generate Summary Badge
        run: |
          chmod +x tools/generate-summary-badges.zsh || true
          tools/generate-summary-badges.zsh

      - name: Determine artifact root
        id: artifact_root
        run: |
          if [ -d docs/redesignv2/artifacts/badges ] && [ -d docs/redesignv2/artifacts/metrics ]; then
            echo "root=docs/redesignv2/artifacts" >> "$GITHUB_OUTPUT"
          else
            echo "root=docs/redesign" >> "$GITHUB_OUTPUT"
          fi
          echo "Selected artifact root: $(grep root= $GITHUB_OUTPUT | cut -d= -f2)"

      - name: Soft bridge (copy new artifacts to legacy paths if using redesignv2)
        if: steps.artifact_root.outputs.root == 'docs/redesignv2/artifacts'
        run: |
          mkdir -p docs/redesign/badges docs/redesign/metrics
          rsync -a --delete docs/redesignv2/artifacts/badges/ docs/redesign/badges/
          rsync -a --delete docs/redesignv2/artifacts/metrics/ docs/redesign/metrics/ || true
          if [ -d docs/redesignv2/artifacts/checksums ]; then
            mkdir -p docs/redesign/checksums
            rsync -a --delete docs/redesignv2/artifacts/checksums/ docs/redesign/checksums/
          fi
          if [ -d docs/redesignv2/artifacts/inventories ]; then
            mkdir -p docs/redesign/inventories
            rsync -a --delete docs/redesignv2/artifacts/inventories/ docs/redesign/inventories/
          fi

      - name: Prepare publish directory
        run: |
          mkdir -p public
          # Prefer new root when publishing
          if [ -d docs/redesignv2/artifacts/badges ]; then
            cp -R docs/redesignv2/artifacts/badges public/
          else
            cp -R docs/redesign/badges public/
          fi
          if [ -d docs/redesignv2/artifacts/metrics ]; then
            cp -R docs/redesignv2/artifacts/metrics public/
          else
            cp -R docs/redesign/metrics public/
          fi
          # Simple index
          cat > public/index.html <<'HTML'
          <html><head><title>ZSH Metrics</title></head><body>
          <h1>ZSH Metrics & Badges</h1>
          <ul>
            <li><a href="badges/perf.json">perf.json</a></li>
            <li><a href="badges/structure.json">structure.json</a></li>
            <li><a href="badges/summary.json">summary.json</a></li>
            <li><a href="metrics/structure-audit.md">structure-audit.md</a></li>
            <li><a href="metrics/perf-current.json">perf-current.json</a></li>
            <li><a href="metrics/perf-baseline.json">perf-baseline.json</a></li>
          </ul>
          <p>Raw badge endpoints can be consumed via shields.io endpoint parameter.</p>
          <p>Source now prefers redesignv2 artifacts (legacy paths bridged temporarily).</p>
          </body></html>
          HTML

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          keep_files: true

      - name: Output Shield URLs
        run: |
          echo "Perf Badge: https://img.shields.io/endpoint?url=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/raw/gh-pages/badges/perf.json"
          echo "Structure Badge: https://img.shields.io/endpoint?url=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/raw/gh-pages/badges/structure.json"
          echo "Summary Badge: https://img.shields.io/endpoint?url=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/raw/gh-pages/badges/summary.json"
