/*
 * wallaby-core - v1.0.1650
 * https://wallabyjs.com
 * Copyright (c) 2014-2024 Wallaby.js - All Rights Reserved.
 *
 * This source code file is a part of wallaby-core and is a proprietary (closed source) software.

 * IMPORTANT:
 * Wallaby.js is a tool made by software developers for software developers with passion and love for what we do.
 * Pirating the tool is not only illegal and just morally wrong,
 * it is also unfair to other fellow programmers who are using it legally,
 * and very harmful for the tool and its future.
 */
var __read=this&&this.__read||function(e,t){var i="function"==typeof Symbol&&e[Symbol.iterator];if(!i)return e;var s,a,r=i.call(e),n=[];try{for(;(void 0===t||0<t--)&&!(s=r.next()).done;)n.push(s.value)}catch(e){a={error:e}}finally{try{s&&!s.done&&(i=r.return)&&i.call(r)}finally{if(a)throw a.error}}return n},__spreadArray=this&&this.__spreadArray||function(e,t,i){if(i||2===arguments.length)for(var s,a=0,r=t.length;a<r;a++)!s&&a in t||((s=s||Array.prototype.slice.call(t,0,a))[a]=t[a]);return e.concat(s||Array.prototype.slice.call(t))},JasmineReporter=function(o){function t(e){if(e&&e.failedExpectations&&e.failedExpectations.length)for(var t=0;t<e.failedExpectations.length;t++){var i=e.failedExpectations[t];i&&!i.matcherName&&"string"==typeof i.message&&"string"==typeof i.stack&&o.reportDeclarationError({message:i.message,stack:i.stack})}}var c=o.initialSpecId(),p=[],u={},s={};this.jasmineStarted=function(e){var i;o.started({total:e.totalSpecsDefined}),jasmineEnv.topSuite&&(i=function(e,t){e.forEach(function(e){e.children?i(e.children,__spreadArray(__spreadArray([],__read(t),!1),[e.description],!1)):e.result&&e.result._testFile&&!e.result._disabled&&(s[e.result._testFile]=s[e.result._testFile]||[],s[e.result._testFile].push({path:__spreadArray(__spreadArray([],__read(t),!1),[e.description],!1),mode:"run"}))})})(jasmineEnv.topSuite().children,[])},this.jasmineDone=function(e){t(e),o.complete()},this.suiteStarted=function(e){p.push(e.description)},this.suiteDone=function(e){t(e),p.pop()},this.specStarted=function(e){s[e._testFile]&&(o.specFileTests([{specFileId:e._testFile,tests:s[e._testFile]}]),delete s[e._testFile]);var t=++c,i=u[e.id]={id:t};o.specStart(t,e.description,e._testFile,__spreadArray(__spreadArray([],__read(p.slice()),!1),[e.description],!1)),i.time=(new o._Date).getTime()},this.specDone=function(e){var t=u[e.id]||{id:c},t=(e._id=t.id,e._time=t.time,delete u[e.id],"passed"===e.status),i="disabled"===e.status||"pending"===e.status||"excluded"===e.status||e._disabled,s=i?"pending"===e.status?"skipped":"excluded"===e.status||"disabled"===e.status?"disabled":"executed":"executed",a=(e._disabled&&(s="disabled"),o.specEnd()),r={id:e._id,timeRange:a,name:e.description,suite:p.slice(),status:s,time:i?0:(new o._Date).getTime()-e._time,log:[],testFile:e._testFile};if(!t&&!i)for(var n=e.failedExpectations,d=0;d<n.length;d++){var l=n[d];l.showDiff=l.showDiff||"toEqual"===l.matcherName,r.log.push(o.setAssertionData(l,{message:l.message,stack:l.stack}))}r.log.length||delete r.log,o.result(r)}},jasmineEnv=jasmine.getEnv(),tracer=window.$_$tracer,adapter=new JasmineReporter(tracer);jasmineEnv.addReporter(adapter);