#!/usr/bin/env bash
set -euo pipefail

echo "Manually fixing zgenom configuration..."
cd /Users/s-a-c/dotfiles/dot-config/zsh

echo "=== 1. Check zgenom directory structure ==="
if [[ -d .zqs-zgenom ]]; then
    echo "zgenom directory exists"
    ls -la .zqs-zgenom/ | head -5
else
    echo "ERROR: zgenom directory missing"
    exit 1
fi

echo ""
echo "=== 2. Clean zgenom state ==="
echo "Removing any corrupted zgenom files..."
rm -f .zqs-zgenom/init.zsh
rm -f .zqs-zgenom/init.zsh.zwc
echo "Cleaned zgenom state"

echo ""
echo "=== 3. Test minimal ZSH with no plugins ==="
echo "Testing if basic ZSH works without plugins..."
timeout 5s bash -c 'ZDOTDIR="$PWD" zsh --no-rcs -c "
    echo \"Basic ZSH works\"
    echo \"PATH has: \$(echo \$PATH | tr : \\n | wc -l) entries\"
    exit
" 2>/dev/null' || echo "Basic ZSH test failed or timed out"

echo ""
echo "=== 4. Try zgenom reset safely ==="
echo "Attempting to reset zgenom in a controlled way..."
timeout 30s bash -c 'ZDOTDIR="$PWD" zsh --no-rcs -c "
    source .zshenv
    source .zqs-zgenom/zgenom.zsh
    echo \"Attempting zgenom reset...\"
    zgenom reset 2>/dev/null || echo \"zgenom reset failed\"
    echo \"zgenom reset attempt completed\"
    exit
" 2>/dev/null' || echo "zgenom reset timed out or failed"

echo ""
echo "=== 5. Check if init.zsh was regenerated ==="
if [[ -f .zqs-zgenom/init.zsh ]]; then
    echo "✅ init.zsh was regenerated"
    echo "First few lines:"
    head -3 .zqs-zgenom/init.zsh
else
    echo "❌ init.zsh was not regenerated"
    echo "Creating minimal init.zsh as fallback..."
    cat > .zqs-zgenom/init.zsh << 'EOF'
# Minimal zgenom init.zsh fallback
# Generated by manual fix script

# Basic plugin loading would go here
# For now, just prevent errors

export ZGENOM_INIT_LOADED=1
EOF
    echo "Created fallback init.zsh"
fi

echo ""
echo "=== 6. Test startup with regenerated init.zsh ==="
timeout 10s bash -c 'ZDOTDIR="$PWD" zsh -i -c "
    echo \"Startup test successful\"
    echo \"STARSHIP_SHELL: \${STARSHIP_SHELL:-not set}\"
    exit
" 2>/dev/null' || echo "Startup test still fails"

echo ""
echo "zgenom fix attempt completed."