version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby

    steps:
      - checkout

      - run:
          name: Install awesome_bot
          command: gem install awesome_bot

      - run:
          name: Check README.md
          command: awesome_bot README.md --allow-dupe --allow-redirect --white-list https://ipfs.io,slideshare,https://img.shields.io,https://codeclimate.com/github/unixorn/warhol.plugin.zsh,www-s.acm.illinois.edu,https://mgdm.net,https://www.concourse.ci
