"--help"="--help 2>&1 | bat --language=help --style=plain"
"-h"="-h 2>&1 | bat --language=help --style=plain"
"...."="../../.."
"....."="../../../.."
"......"="../../../../.."
"@NDL"="~/Downloads/*(.om[1])"
"bathelp"="bat --plain --language=help"
"g"="git"
"git co"="git checkout"
"git cp"="git cherry-pick"
"-"="cd -"
".."="cd .."
"..."="cd ../.."
"1"="cd -1"
"2"="cd -2"
"3"="cd -3"
"4"="cd -4"
"5"="cd -5"
"6"="cd -6"
"7"="cd -7"
"8"="cd -8"
"9"="cd -9"
":q"="exit"
"_"="sudo "
"airport"="/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport"
"annotate"="git annotate"
"artisan"="php artisan"
"asroot"="sudo \$(fc -ln -1)"
"ba"="brew autoremove"
"bci"="brew info --cask"
"bcin"="brew install --cask"
"bcl"="brew list --cask"
"bcn"="brew cleanup"
"bco"="brew outdated --cask"
"bcrin"="brew reinstall --cask"
"bcubc"="brew upgrade --cask && brew cleanup"
"bcubo"="brew update && brew outdated --cask"
"bcup"="brew upgrade --cask"
"bfu"="brew upgrade --formula"
"bi"="brew install"
"bl"="brew list"
"blame"="git blame"
"bo"="brew outdated"
"bob"="php artisan bob::build"
"brewp"="brew pin"
"brewsp"="brew list --pinned"
"bsl"="brew services list"
"bsoff"="brew services stop"
"bsoffa"="brew services stop --all"
"bson"="brew services start"
"bsona"="bson --all"
"bsr"="brew services run"
"bsra"="bsr --all"
"bu"="brew update"
"bubc"="brew upgrade && brew cleanup"
"bubo"="brew update && brew outdated"
"bubu"="brew update && brew outdated && brew upgrade && brew cleanup"
"bubug"="brew update && brew outdated && brew upgrade --greedy && brew cleanup"
"bugbc"="brew upgrade --greedy && brew cleanup"
"bup"="brew upgrade"
"buz"="brew uninstall --zap"
"c"="composer"
"cadd"="code -a"
"ccat"="colorize_cat"
"ccp"="composer create-project"
"cd"="z"
"cdiff"="code -d"
"cdo"="composer dump-autoload -o"
"cdu"="composer dump-autoload"
"cget"="curl -s https://getcomposer.org/installer | php"
"cgr"="composer global require"
"cgrm"="composer global remove"
"cgu"="composer global update"
"chgext"="change-extension"
"ci"="composer install"
"cleanxmlclip"="clean-xml-clip"
"cless"="colorize_less"
"cnew"="code -n"
"co"="composer outdated"
"cod"="composer outdated --direct"
"code-install"="code --install-extension"
"code-uninstall"="code --uninstall-extension"
"cr"="composer require"
"crm"="composer remove"
"cs"="composer show"
"csu"="composer self-update"
"cu"="composer update"
"cuh"="composer update --working-dir=\$(composer config -g home)"
"d"="desk"
"d."="desk ."
"d.."="desk .."
"da"="dotnet add"
"dat"="docker attach"
"date_locale"="date +%c"
"db"="dotnet build"
"dbu"="docker build"
"dc"="deno compile"
"dca"="deno cache"
"dco"="docker commit"
"dde"="docker export"
"ddi"="docker diff"
"DELETE"="lwp-request -m 'DELETE'"
"dfmt"="deno fmt"
"dh"="deno help"
"dhi"="docker history"
"dicepass"="perl -MCrypt::XkcdPassword -e 'print Crypt::XkcdPassword->make_password(\$_)'"
"dim"="docker images"
"dimp"="docker import"
"din"="docker info"
"dins"="docker insert"
"dinsp"="docker inspect"
"disablehistory"="function zshaddhistory() {  return 1 }"
"dk"="docker kill"
"dli"="deno lint"
"dlogin"="docker login"
"dlogs"="docker logs"
"dmesg"="sudo dmesg"
"dn"="dotnet new"
"dng"="dotnet nuget"
"dp"="dotnet pack"
"dport"="docker port"
"dps"="docker ps"
"dpull"="docker pull"
"dpush"="docker push"
"dr"="dotnet run"
"drA"="deno run -A"
"dre"="docker restart"
"drm"="docker rm"
"drmi"="docker rmi"
"drn"="deno run"
"dru"="deno run --unstable"
"drun"="docker run"
"drw"="deno run --watch"
"ds"="dotnet sln"
"dse"="docker search"
"dstart"="docker start"
"dstop"="docker stop"
"dt"="dotnet test"
"dtag"="docker tag"
"dtop"="docker top"
"dts"="deno test"
"dup"="deno upgrade"
"dversion"="docker version"
"dw"="dotnet watch"
"dwait"="docker wait"
"dwr"="dotnet watch run"
"dwt"="dotnet watch test"
"e"="emacs"
"edit"="/opt/homebrew/bin/nvim \$(eval \${\$(fc -l -1)[2,-1]} -l)"
"eeval"="/Users/s-a-c/.config/zsh/.zgenom/ohmyzsh/ohmyzsh/___/plugins/emacs/emacsclient.sh --eval"
"eframe"="emacsclient --alternate-editor=\"\" --create-frame"
"egrep"="grep -E"
"eject"="diskutil eject"
"emacs"="/Users/s-a-c/.config/zsh/.zgenom/ohmyzsh/ohmyzsh/___/plugins/emacs/emacsclient.sh --no-wait"
"enablehistory"="unset -f zshaddhistory"
"external_ip"="curl -s icanhazip.com"
"eza"="eza --classify --color=always --color-scale --group-directories-first --hyperlink --icons"
"fcd"="fzf-change-directory"
"fgrep"="grep -F"
"fkill"="fzf-kill"
"flush-osx-cache"="flu.sh"
"flushdns"="dscacheutil -flushcache"
"flushds"="dscacheutil -flushcache"
"fsh-alias"="fast-theme"
"g"="git"
"ga"="git add"
"gaa"="git add --all"
"gadd"="git add"
"gam"="git am"
"gama"="git am --abort"
"gamc"="git am --continue"
"gams"="git am --skip"
"gamscp"="git am --show-current-patch"
"gap"="git apply"
"gapa"="git add --patch"
"gapt"="git apply --3way"
"gau"="git add --update"
"gav"="git add --verbose"
"gb"="git branch"
"gba"="git branch --all"
"gbD"="git branch --delete --force"
"gbd"="git branch --delete"
"gbg"="LANG=C git branch -vv | grep \": gone\]\""
"gbgd"="LANG=C git branch --no-color -vv | grep \": gone\]\" | cut -c 3- | awk '{print \$1}' | xargs git branch -d"
"gbgD"="LANG=C git branch --no-color -vv | grep \": gone\]\" | cut -c 3- | awk '{print \$1}' | xargs git branch -D"
"gbl"="git blame -w"
"gblame"="git blame"
"gbm"="git branch --move"
"gbnm"="git branch --no-merged"
"gbr"="git branch --remote"
"gbs"="git bisect"
"gbsb"="git bisect bad"
"gbsg"="git bisect good"
"gbsn"="git bisect new"
"gbso"="git bisect old"
"gbsr"="git bisect reset"
"gbss"="git bisect start"
"gc"="git commit --verbose"
"gc\!"="git commit --verbose --amend"
"gc\\!"="git commit --verbose --amend"
"gca"="git commit --verbose --all"
"gca\!"="git commit --verbose --all --amend"
"gca\\!"="git commit --verbose --all --amend"
"gcam"="git commit --all --message"
"gcan\!"="git commit --verbose --all --no-edit --amend"
"gcan\\!"="git commit --verbose --all --no-edit --amend"
"gcann\!"="git commit --verbose --all --date=now --no-edit --amend"
"gcann\\!"="git commit --verbose --all --date=now --no-edit --amend"
"gcans\!"="git commit --verbose --all --signoff --no-edit --amend"
"gcans\\!"="git commit --verbose --all --signoff --no-edit --amend"
"gcas"="git commit --all --signoff"
"gcasm"="git commit --all --signoff --message"
"gcB"="git checkout -B"
"gcb"="git checkout -b"
"gcd"="git checkout \$(git_develop_branch)"
"gcf"="git config --list"
"gci"="git ci -v"
"gcl"="git clone --recurse-submodules"
"gclean"="git clean --interactive -d"
"gclf"="git clone --recursive --shallow-submodules --filter=blob:none --also-filter-submodules"
"gcm"="git checkout \$(git_main_branch)"
"gcmsg"="git commit --message"
"gcn"="git commit --verbose --no-edit"
"gcn\!"="git commit --verbose --no-edit --amend"
"gcn\\!"="git commit --verbose --no-edit --amend"
"gco"="git checkout"
"gcor"="git checkout --recurse-submodules"
"gcount"="git shortlog --summary --numbered"
"gcp"="git cherry-pick"
"gcpa"="git cherry-pick --abort"
"gcpc"="git cherry-pick --continue"
"gcs"="git commit --gpg-sign"
"gcsm"="git commit --signoff --message"
"gcss"="git commit --gpg-sign --signoff"
"gcssm"="git commit --gpg-sign --signoff --message"
"gd"="git diff"
"gdca"="git diff --cached"
"gdct"="git describe --tags \$(git rev-list --tags --max-count=1)"
"gdcw"="git diff --cached --word-diff"
"gdiff"="git diff"
"gds"="git diff --staged"
"gdt"="git diff-tree --no-commit-id --name-only -r"
"gdup"="git diff @{upstream}"
"gdw"="git diff --word-diff"
"gemb"="gem build *.gemspec"
"gemp"="gem push *.gem"
"gerp"="grep"
"GET"="lwp-request -m 'GET'"
"get-file-modification-time"="get_file_modification_time"
"get_nr_jobs"="get-nr-jobs"
"gf"="git fetch"
"gfa"="git fetch --all --tags --prune --jobs=10"
"gfg"="git ls-files | grep"
"gfo"="git fetch origin"
"gg"="git gui citool"
"gga"="git gui citool --amend"
"ggpull"="git pull origin \"\$(git_current_branch)\""
"ggpur"="ggu"
"ggpush"="git push origin \"\$(git_current_branch)\""
"ggsup"="git branch --set-upstream-to=origin/\$(git_current_branch)"
"ghh"="git help"
"gignore"="git update-index --assume-unchanged"
"gignored"="git ls-files -v | grep \"^[[:lower:]]\""
"git-cdroot"="cd \$(git rev-parse --show-toplevel) && echo \"\$_\""
"git-grab"="git-incoming-commits"
"git-ignored"="git ls-files --others --i --exclude-standard"
"git-svn-dcommit-push"="git svn dcommit && git push github \$(git_main_branch):svntrunk"
"gitadd"="git add"
"gitci"="git ci -v"
"gitdiff"="git diff"
"gitignored"="git ls-files --others --i --exclude-standard"
"gitlgg"="git log --pretty=format:'%Cred%h%Creset -%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'"
"gitlog"="git log"
"gitloll"="git log --graph --decorate --pretty=oneline --abbrev-commit"
"gitmerge"="git merge"
"gitpull"="git pull"
"gitpus"="git push"
"gitpush"="git push"
"gitrebase"="git rebase"
"gitroot"="cd \$(git rev-parse --show-toplevel) && echo \"\$_\""
"gitst"="git status"
"gk"="\gitk --all --branches &\\\!"
"gke"="\gitk --all \$(git log --walk-reflogs --pretty=%h) &\\\!"
"gl"="git pull"
"glg"="git log --stat"
"glgg"="git log --graph"
"glgga"="git log --graph --decorate --all"
"glgm"="git log --graph --max-count=10"
"glgp"="git log --stat --patch"
"glo"="git log --oneline --decorate"
"glod"="git log --graph --pretty=\"%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset\""
"glods"="git log --graph --pretty=\"%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset\" --date=short"
"glog"="git log --oneline --decorate --graph"
"gloga"="git log --oneline --decorate --graph --all"
"glol"="git log --graph --pretty=\"%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset\""
"glola"="git log --graph --pretty=\"%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset\" --all"
"glols"="git log --graph --pretty=\"%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset\" --stat"
"glp"="_git_log_prettily"
"gluc"="git pull upstream \$(git_current_branch)"
"glum"="git pull upstream \$(git_main_branch)"
"gm"="git merge"
"gma"="git merge --abort"
"gmc"="git merge --continue"
"gmff"="git merge --ff-only"
"gmom"="git merge origin/\$(git_main_branch)"
"gms"="git merge --squash"
"gmtl"="git mergetool --no-prompt"
"gmtlvim"="git mergetool --no-prompt --tool=vimdiff"
"gmum"="git merge upstream/\$(git_main_branch)"
"gob"="go build"
"goc"="go clean"
"god"="go doc"
"goe"="go env"
"gof"="go fmt"
"gofa"="go fmt ./..."
"gofx"="go fix"
"gog"="go get"
"goga"="go get ./..."
"goi"="go install"
"gol"="go list"
"gom"="go mod"
"gomt"="go mod tidy"
"gopa"="cd \$GOPATH"
"gopb"="cd \$GOPATH/bin"
"gops"="cd \$GOPATH/src"
"gor"="go run"
"got"="go test"
"gota"="go test ./..."
"goto"="go tool"
"gotoc"="go tool compile"
"gotod"="go tool dist"
"gotofx"="go tool fix"
"gov"="go vet"
"gove"="go version"
"gow"="go work"
"gp"="git push"
"gpaste"="\"pbpaste | perl -pe 's/"
"gpd"="git push --dry-run"
"gpf"="git push --force-with-lease --force-if-includes"
"gpf\!"="git push --force"
"gpf\\!"="git push --force"
"gpoat"="git push origin --all && git push origin --tags"
"gpod"="git push origin --delete"
"gpr"="git pull --rebase"
"gpra"="git pull --rebase --autostash"
"gprav"="git pull --rebase --autostash -v"
"gpristine"="git reset --hard && git clean --force -dfx"
"gprom"="git pull --rebase origin \$(git_main_branch)"
"gpromi"="git pull --rebase=interactive origin \$(git_main_branch)"
"gprum"="git pull --rebase upstream \$(git_main_branch)"
"gprumi"="git pull --rebase=interactive upstream \$(git_main_branch)"
"gprv"="git pull --rebase -v"
"gpsup"="git push --set-upstream origin \$(git_current_branch)"
"gpsupf"="git push --set-upstream origin \$(git_current_branch) --force-with-lease --force-if-includes"
"gpu"="git push upstream"
"gpull"="git pull"
"gpush"="git push"
"gpv"="git push --verbose"
"gr"="git remote"
"gra"="git remote add"
"grb"="git rebase"
"grba"="git rebase --abort"
"grbc"="git rebase --continue"
"grbd"="git rebase \$(git_develop_branch)"
"grbi"="git rebase --interactive"
"grbm"="git rebase \$(git_main_branch)"
"grbo"="git rebase --onto"
"grbom"="git rebase origin/\$(git_main_branch)"
"grbs"="git rebase --skip"
"grbum"="git rebase upstream/\$(git_main_branch)"
"grebase"="git rebase -i"
"grep"="GREP_COLORS=\"1;37;41\" LANG=C grep --color=auto"
"grep-i"="grep -i"
"grepi"="grep -i"
"grepm"="grep --exclude-dir={node_modules,bower_components,dist,.bzr,.cvs,.git,.hg,.svn,.tmp} --color=always"
"grev"="git revert"
"greva"="git revert --abort"
"grevc"="git revert --continue"
"grf"="git reflog"
"grh"="git reset"
"grhh"="git reset --hard"
"grhk"="git reset --keep"
"grhs"="git reset --soft"
"grm"="git rm"
"grmc"="git rm --cached"
"grmv"="git remote rename"
"groh"="git reset origin/\$(git_current_branch) --hard"
"grrm"="git remote remove"
"grs"="git restore"
"grset"="git remote set-url"
"grss"="git restore --source"
"grst"="git restore --staged"
"grt"="cd \"\$(git rev-parse --show-toplevel || echo .)\""
"gru"="git reset --"
"grup"="git remote update"
"grv"="git remote --verbose"
"gsb"="git status --short --branch"
"gsd"="git svn dcommit"
"gsh"="git show"
"gsi"="git submodule init"
"gsps"="git show --pretty=short --show-signature"
"gsr"="git svn rebase"
"gss"="git status --short"
"gst"="git status"
"gsta"="git stash push"
"gstaa"="git stash apply"
"gstall"="git stash --all"
"gstc"="git stash clear"
"gstd"="git stash drop"
"gstl"="git stash list"
"gstp"="git stash pop"
"gsts"="git stash show --patch"
"gstu"="gsta --include-untracked"
"gsu"="git submodule update"
"gsw"="git switch"
"gswc"="git switch --create"
"gswd"="git switch \$(git_develop_branch)"
"gswm"="git switch \$(git_main_branch)"
"gta"="git tag --annotate"
"gtl"="gtl(){ git tag --sort=-v:refname -n --list \"\${1}*\" }; noglob gtl"
"gts"="git tag --sign"
"gtv"="git tag | sort -V"
"gunignore"="git update-index --no-assume-unchanged"
"gunwip"="git rev-list --max-count=1 --format=\"%s\" HEAD | grep -q \"\--wip--\" && git reset HEAD~1"
"gup"="\""
"gupa"="\""
"gupav"="\""
"gupom"="\""
"gupomi"="\""
"gupv"="\""
"gwch"="git whatchanged -p --abbrev-commit --pretty=medium"
"gwip"="git add -A; git rm \$(git ls-files --deleted) 2> /dev/null; git commit --no-verify --no-gpg-sign --message \"--wip-- [skip ci]\""
"gwipe"="git reset --hard && git clean --force -df"
"gwt"="git worktree"
"gwta"="git worktree add"
"gwtls"="git worktree list"
"gwtmv"="git worktree move"
"gwtrm"="git worktree remove"
"hd"="hexdump -C"
"HEAD"="lwp-request -m 'HEAD'"
"hidefiles"="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"
"history"="omz_history"
"historysummary"="\"history | awk '{a[\\$2]++} END{for(i in a){printf \\"%5d	%s"
"hlog"="git log --all --date-order --graph --date=short --format=\"%C(green)%H%Creset %C(yellow)%an%Creset %C(blue bold)%ad%Creset %C(red bold)%d%Creset%s\""
"httpdump"="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""
"ips"="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print '"
"isodate"="date +%Y-%m-%dT%H:%M:%S%z"
"isodate_basic"="date -u +%Y%m%dT%H%M%SZ"
"isodate_utc"="date -u +%Y-%m-%dT%H:%M:%SZ"
"kickdns"="dscacheutil -flushcache"
"killScreenSaver"="kill-screensaver"
"killSS"="kill-screensaver"
"knfie"="knife"
"knife"="nocorrect knife"
"ksvim"="NVIM_APPNAME=nvim-Kickstart nvim"
"l"="eza"
"la"="eza --git --all"
"latest-perl"="curl -s https://www.perl.org/get.html | perl -wlne 'if (/perl\-([\d\.]+)\.tar\.gz/) { print \$1; exit;}'"
"lD"="eza --long --header --git --sort=date"
"lDa"="eza --long --header --git --sort=date --all"
"lDD"="eza -ghlDa --group-directories-first --git --icons=auto --hyperlink"
"ldot"="eza -ghld --group-directories-first --git --icons=auto --hyperlink .*"
"lDr"="eza --long --header --git --sort=date --reverse"
"lDra"="eza --long --header --git --sort=date --reverse --all"
"less"="bat"
"ll"="eza --long --header --git --all --level=2"
"lmvim"="NVIM_APPNAME=nvim-Lazyman nvim"
"lR"="eza --long --header --git --sort=reverse"
"lRa"="eza --long --header --git --sort=reverse --all"
"lRr"="eza --long --header --git --sort=reverse --reverse"
"lRra"="eza --long --header --git --sort=reverse --reverse --all"
"ls"="eza --git"
"lS"="eza --long --header --git --sort=size"
"lSa"="eza --long --header --git --sort=size --all"
"lsa"="ls -lah"
"lsd"="eza -ghd --group-directories-first --git --icons=auto --hyperlink"
"lsdl"="eza -ghdl --group-directories-first --git --icons=auto --hyperlink"
"lSr"="eza --long --header --git --sort=size --reverse"
"lSra"="eza --long --header --git --sort=size --reverse --all"
"lss"="lsd --group-dirs first"
"lt"="eza --long --header --git --tree"
"lT"="eza --long --header --git --sort=type"
"lTa"="eza --long --header --git --sort=type --all"
"lta"="eza --long --header --git --tree --all"
"ltr"="eza --long --header --git --tree --reverse"
"lTr"="eza --long --header --git --sort=type --reverse"
"lTra"="eza --long --header --git --sort=type --reverse --all"
"ltra"="eza --long --header --git --tree --reverse --all"
"lU"="eza --long --header --git --sort=none"
"lUa"="eza --long --header --git --sort=none --all"
"lUr"="eza --long --header --git --sort=none --reverse"
"lUra"="eza --long --header --git --sort=none --reverse --all"
"lx"="eza --long --header --git --sort=extension"
"lX"="eza --long --header --git --sort=extension --reverse"
"lXa"="eza --long --header --git --sort=extension --reverse --all"
"lxa"="eza --long --header --git --sort=extension --all"
"lXr"="eza --long --header --git --sort=extension --reverse"
"lXra"="eza --long --header --git --sort=extension --reverse --all"
"lz"="eza --long --header --git --sort=extension --reverse"
"lZ"="eza --long --header --git --sort=extension"
"lza"="eza --long --header --git --sort=extension --all"
"lZa"="eza --long --header --git --sort=extension --reverse --all"
"lZr"="eza --long --header --git --sort=extension --reverse"
"lZra"="eza --long --header --git --sort=extension --reverse --all"
"mac2unix"="\"tr '' '"
"maek"="make"
"man"="batman"
"md"="mkdir -p"
"md5sum"="/sbin/md5"
"mkdir-p"="mkdir -p"
"mkdirp"="mkdir -p"
"mtr_url"="mtr-url"
"my_ips"="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print '"
"myip"="dig +short myip.opendns.com @resolver1.opendns.com"
"mywireless"="wifi-name"
"naliases"="n-aliases"
"ncd"="n-cd"
"nenv"="n-env"
"nfunctions"="n-functions"
"nh-scp"="scp-no-hostchecks"
"nh-ssh"="ssh-no-hostchecks"
"nh_scp"="scp-no-hostchecks"
"nh_ssh"="ssh-no-hostchecks"
"nhelp"="n-help"
"nhistory"="n-history"
"nhscp"="scp-no-hostchecks"
"nhssh"="ssh-no-hostchecks"
"nkill"="n-kill"
"noptions"="n-options"
"npanelize"="n-panelize"
"npmD"="npm i -D "
"npmE"="PATH=\"\$(npm bin)\":\"\$PATH\""
"npmF"="npm i -f"
"npmg"="npm i -g "
"npmI"="npm init"
"npmi"="npm info"
"npmL"="npm list"
"npmL0"="npm ls --depth=0"
"npmO"="npm outdated"
"npmP"="npm publish"
"npmR"="npm run"
"npmrb"="npm run build"
"npmrd"="npm run dev"
"npmS"="npm i -S "
"npmSe"="npm search"
"npmst"="npm start"
"npmt"="npm test"
"npmU"="npm update"
"npmV"="npm -v"
"nvim-default"="NVIM_APPNAME=nvim nvim"
"nvim-Kickstart"="NVIM_APPNAME=nvim-Kickstart nvim"
"nvim-Lazyman"="NVIM_APPNAME=nvim-Lazyman nvim"
"OPTIONS"="lwp-request -m 'OPTIONS'"
"pacac"="php artisan cache:clear"
"pacoc"="php artisan config:clear"
"pads"="php artisan db:seed"
"pam"="php artisan migrate"
"pamc"="php artisan make:controller"
"pamcl"="php artisan make:class"
"pame"="php artisan make:event"
"pamen"="php artisan make:enum"
"pamf"="php artisan migrate:fresh"
"pamfa"="php artisan make:factory"
"pamfs"="php artisan migrate:fresh --seed"
"pami"="php artisan make:interface"
"pamj"="php artisan make:job"
"paml"="php artisan make:listener"
"pamm"="php artisan make:model"
"pamn"="php artisan make:notification"
"pamp"="php artisan make:policy"
"pampp"="php artisan make:provider"
"pamr"="php artisan migrate:rollback"
"pams"="php artisan make:seeder"
"pamt"="php artisan make:test"
"pamtr"="php artisan make:trait"
"paopc"="php artisan optimize:clear"
"paqf"="php artisan queue:failed"
"paqft"="php artisan queue:failed-table"
"paql"="php artisan queue:listen"
"paqr"="php artisan queue:retry"
"paqt"="php artisan queue:table"
"paqw"="php artisan queue:work"
"paroc"="php artisan route:clear"
"pas"="php artisan serve"
"pats"="php artisan test"
"pavic"="php artisan view:clear"
"pbi"="perlbrew install"
"pbl"="perlbrew list"
"pbo"="perlbrew off"
"pbs"="perlbrew switch"
"pbu"="perlbrew use"
"pd"="perldoc"
"perl-grep"="pgrep"
"perlgrep"="pgrep"
"pip"="noglob pip3"
"pipgi"="pip freeze | grep"
"pipi"="pip install"
"pipir"="pip install -r requirements.txt"
"piplo"="pip list -o"
"pipreq"="pip freeze > requirements.txt"
"pipu"="pip install --upgrade"
"pipun"="pip uninstall"
"pl-grep"="pgrep"
"ple"="perl -wlne"
"POST"="lwp-request -m 'POST'"
"procs_for_path"="procs-for-path"
"psax"="ps ax"
"pswax"="ps wax"
"psxa"="ps ax"
"PUT"="lwp-request -m 'PUT'"
"py"="python3"
"pyfind"="find . -name \"*.py\""
"pygrep"="grep -nr --include=\"*.py\""
"pyserver"="python3 -m http.server"
"python_module_path"="echo 'import sys; t=__import__(sys.argv[1],fromlist=[\".\"]); print(t.__file__)'  | python - "
"ql"="qlmanage -p"
"raek"="rake"
"rd"="rmdir"
"reattach"="screen -r"
"reveal"="open --reveal"
"rm"="echo \"This is not the command you are looking for.\"; false"
"rsync-copy"="rsync -avz --progress -h"
"rsync-move"="rsync -avz --progress -h --remove-source-files"
"rsync-synchronize"="rsync -avzu --delete --progress -h"
"rsync-update"="rsync -avzu --progress -h"
"rubies"="chruby"
"run-help"="man"
"scp-no-hostchecks"="scp -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
"scp_no_hostchecks"="scp -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
"scpi"="scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null"
"sha1sum"="/opt/homebrew/bin/shasum"
"showfiles"="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
"sign"="gpg --detach-sign --armor"
"snake_case"="tr [A-Z\ ] [a-z_]"
"sniff"="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
"spotlighter"="mdfind -onlyin \`pwd\`"
"ssh"="ssh -A"
"ssh-A"="ssh -A"
"ssh-addme"="sshaddme"
"ssh-force-password"="ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no"
"ssh-force-password-no-hostcheck"="ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null"
"ssh-no-hostchecks"="ssh -A -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
"ssh-unkeyed"="/usr/bin/ssh"
"ssh_no_hostchecks"="ssh -A -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
"ssh_unkeyed"="/usr/bin/ssh"
"sshA"="ssh -A"
"sshi"="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null"
"sshnohostchecks"="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null"
"stripcolors"="sed -r \"s/\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g\""
"tar-tvf"="tar tvf"
"tar-tvzf"="tar tvzf"
"tar-xvf"="tar xvf"
"tar-xvzf"="tar xvzf"
"tartvf"="tar tvf"
"tartvzf"="tar tvzf"
"tarxvf"="tar xvf"
"tarxvjf"="tar xvjf"
"tarxvzf"="tar xvzf"
"tds"="_tmux_directory_session"
"te"="/Users/s-a-c/.config/zsh/.zgenom/ohmyzsh/ohmyzsh/___/plugins/emacs/emacsclient.sh -nw"
"test-broadband"="wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test500.zip"
"tksv"="tmux kill-server"
"tl"="tmux list-sessions"
"tldrf"="tldr --list | fzf --preview \"tldr {1} --color=always\" --preview-window=right:70% | xargs tldr --color=always"
"tmux"="_zsh_tmux_plugin_run"
"tmuxconf"="\$EDITOR \$ZSH_TMUX_CONFIG"
"top"="TERM=vt100 top"
"TRACE"="lwp-request -m 'TRACE'"
"trash"="trash-put"
"tree"="eza --long --header --git --tree"
"treea"="eza --long --header --git --tree --all"
"unix2mac"="\"tr '"
"unixstamp"="date +%s"
"updatedb"="sudo /usr/libexec/locate.updatedb"
"vba"="vagrant box add"
"vbl"="vagrant box list"
"vbo"="vagrant box outdated"
"vbr"="vagrant box remove"
"vbu"="vagrant box update"
"vd"="vagrant destroy"
"vdf"="vagrant destroy -f"
"vgi"="vagrant init"
"vgs"="vagrant global-status"
"vh"="vagrant halt"
"vi"="/run/current-system/sw/bin/vim"
"vim"="/run/current-system/sw/bin/vim"
"vp"="vagrant push"
"vpli"="vagrant plugin install"
"vpll"="vagrant plugin list"
"vplu"="vagrant plugin update"
"vplun"="vagrant plugin uninstall"
"vpr"="vagrant provision"
"vr"="vagrant reload"
"vrdp"="vagrant rdp"
"vre"="vagrant resume"
"vrp"="vagrant reload --provision"
"vs-code"="code"
"vscode"="code"
"vsh"="vagrant share"
"vssh"="vagrant ssh"
"vsshc"="vagrant ssh-config"
"vssp"="vagrant suspend"
"vst"="vagrant status"
"vup"="vagrant up"
"wcat"="wget -q -O -"
"wget"="wget -c"
"wget-images"="wget -nd -r -l 2 -A jpg,jpeg,png,gif,bmp"
"which-command"="whence"
"xcb"="xcodebuild"
"xcdd"="rm -rf ~/Library/Developer/Xcode/DerivedData/*"
"xcp"="xcode-select --print-path"
"xcsel"="sudo xcode-select --switch"
"zh"="fc -l -d -D"
"zombies"="zombie"
"zz"="exit"
