name: Nightly Secret Scan

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch: {}

permissions:
  contents: read
  security-events: write

concurrency:
  group: nightly-secrets-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks-nightly:
    name: Gitleaks Nightly Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --verbose --redact --report-format sarif --report-path gitleaks.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: gitleaks.sarif

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nightly-gitleaks-report
          path: gitleaks.sarif
          if-no-files-found: ignore

      - name: Slack notify on findings (optional)
        if: failure() && secrets.SECURITY_ALERTS_SLACK_WEBHOOK != ''
        env:
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          REPO: ${{ github.repository }}
          WEBHOOK: ${{ secrets.SECURITY_ALERTS_SLACK_WEBHOOK }}
        run: |
          msg="Gitleaks found potential secrets in $REPO — $RUN_URL"
          payload=$(printf '{"text":"%s"}' "$msg")
          curl -sS -X POST -H 'Content-type: application/json' --data "$payload" "$WEBHOOK"
